# Generated by Django 2.1.7 on 2019-06-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.UUIDField(),
        ),
    ]
