# Generated by Django 2.1.7 on 2019-06-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_firmware_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealthStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=150)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            options={
                'ordering': ['-stamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceSensorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_type', models.CharField(choices=[('TM', 'Temperature (in Celsius)'), ('HM', 'Air humidity percentage'), ('CO', 'Carbon Monoxide level in the air (PPM)')], default='TM', max_length=2)),
                ('value', models.DecimalField(decimal_places=5, max_digits=8)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            options={
                'ordering': ['-stamp'],
                'abstract': False,
            },
        ),
    ]
